### ISSUE TITLE
Tests panicked at 'Failed to load Postgres connect URL: NotPresent'

### ISSUE THREAD

**Issue by laxect** [mythal/boluo-server#1]
> ---- channels::models::channel_member_test stdout ----
> thread 'channels::models::channel_member_test' panicked at 'Failed to load Postgres connect URL: NotPresent', src/libcore/result.rs:1192:5

**Comment by uonr** [comment]
the `.env` is not loaded in test, you should load it manually:

```
export $(cat .env | xargs)
cargo test
```

or

```
DATABASE_URL="postgresql://postgres:POSTGRES_PASSWORD@db/boluo" REDIS_URL="redis://127.0.0.1/" SECRET="some_secret" cargo test
```
or (in Clion)

![image](https://user-images.githubusercontent.com/34709816/72169123-775aa280-3409-11ea-8955-01fdc3769e2d.png)
