### ISSUE TITLE
Images uploading failed: I/O error has occurred

### ISSUE THREAD

**Issue by HolgerHuo** [mythal/boluo-server#3]
When uploading images (chat/avatar), server backend shows "an I/O error has occured" and in Nginx it shows Connection failed(to upstream) with error code 500.

I'm not sure if it's the issue with nginx or server code.

**Comment by uonr** [comment]
Maybe you can try to create a `./media/` directory in project root (I will attempt to reproduce)

**Comment by HolgerHuo** [comment]
> Maybe you can try to create a ./media/ directory in project root (I will attempt to reproduce)

Should it be under the Nginx root where the frontend build is or under the home directory of the running user?

I'll try it under both directories after work. Thanks a lot for your help! 😉

**Comment by uonr** [comment]
> Should it be under the Nginx root where the frontend build is or under the home directory of the running user?

under the `boluo-server/`directory

**Comment by HolgerHuo** [comment]
Thanks for your help!

I've tested it and it seems that creating the folder under running user's home directory worked (under `boluo-server/` where boluo-server was built didn't seem to work for me. I think the compiling directory shouldn't have more effects after compiling🤔 I'm not sure about that since I'm no familiar with Rust.)

Thanks again for your help and creating the wonderful server for coc!

Stay safe.

**Comment by uonr** [comment]
thanks for report. reopen it because I should add some code or document for create media folder
